const path = require("path");
const mongodb = require("mongodb");
require("dotenv").config();
const passport = require("passport");
const cors = require("cors");
const GitHubStrategy = require("passport-github2");
const session = require("express-session");
const express = require("express"),
  app = express();
const bodyParser = require("body-parser"); // middleware for parsing body
const User = require("./model/users.js");
const Tasks = require("./model/tasks.js");
const LocalStrategy = require("passport-local").Strategy;
const ObjectId = require("mongodb").ObjectId;

const verifyUserLoggedIn = function (req, res, cb) {};

// TODO: unsure serve rest of the files, has to be in the bottomish
app.use(express.static("../client/build/"));

app.use(
  cors({
    credentials: true,
  })
);
app.use(bodyParser.urlencoded({ extended: true }));

app.use(
  session({
    secret: process.env.SESSION_SECRET,
    resave: false,
    saveUninitialized: true,
    cookie: { maxAge: 3600000, secure: false },
  })
);
app.use(passport.initialize());
app.use(passport.session());

// Middlewares

// Local strategy generated by passport-local-mongoose
passport.use(new LocalStrategy(User.authenticate()));

// github strategy for oauth connection
passport.use(
  new GitHubStrategy(
    {
      clientID: process.env.CLIENT_ID,
      clientSecret: process.env.CLIENT_SECRET,
      callbackURL: "http://localhost:3000/auth/github/callback",
    },
    function (accessToken, refreshToken, profile, done) {
      process.nextTick(function () {
        User.findByUsername(profile.username)
          .exec()
          .then((user) => {
            if (!user) {
              // no user with this username, create one
              User.register(
                { username: profile.username },
                profile.id,
                (err, account) => {
                  if (err) {
                    console.log(err);
                  } else {
                    done(null, account);
                  }
                }
              );
            } else {
              done(null, user);
            }
          });
      });
    }
  )
);

// Session Management
passport.serializeUser(User.serializeUser());
passport.deserializeUser(User.deserializeUser());

app.get(
  "/auth/github/callback",
  passport.authenticate("github", {
    failureRedirect: "/login",
    failureMessage: true,
  }),
  function (req, res) {
    console.log("AUTHENTICATION: Github account");
    res.redirect("/index");
  }
);

// Github authentication
app.get(
  "/auth/github",
  passport.authenticate("github", { scope: ["user:email"] }),
  function (req, res) {}
);

//, { failureRedirect: '/login', failureMessage:true}
// handle login attempt
app.post("/login", function (req, res, next) {
  passport.authenticate("local", function (err, user, info) {
    if (user) {
      // user exists
      //res.redirect("http://localhost:8080/test");
      console.log("user logged in");
      res.status(200).send({ isG: "All G" });
    } else {
      res.status(401).send({ isG: "Not G" });
    }
  })(req, res, next);

  //res.redirect('/index');
});

// local mongoose db
app.get("/", function (req, res) {
  console.log("get /");
  if (req.isAuthenticated()) {
    res.send({ msg: "allG" });
    // res.sendFile(__dirname + "/public/index.html");
  } else {
    res.send({ msg: "Not g" });

    // res.sendFile(__dirname + '/public/login.html');
  }
});

app.get("/auth/status", function (req, res) {
  console.log("-----------------------------");
  console.log("/auth/status");
  console.log(req);

  if (req.user) {
    console.log("Auth is true");
    res.writeHeader(200, { "Content-Type": "application/json" });
    res.end(JSON.stringify({ isAuth: true }));
  } else {
    console.log("Auth is false");
    res.writeHeader(200, { "Content-Type": "application/json" });
    res.end(JSON.stringify({ isAuth: false }));
  }
});

app.get("/index", connectEnsureLogin.ensureLoggedIn(), (req, res) => {
  console.log("get /index");
  res.send({ msg: "allG" });
});

app.get("/login", function (req, res) {
  console.log("get /login");
  //res.sendFile(__dirname + "/public/login.html")
});

app.get("/logout", function (req, res, next) {
  req.logout(function (err) {
    if (err) {
      return next(err);
    }
    res.redirect("/");
  });
});

app.get("/username", connectEnsureLogin.ensureLoggedIn(), function (req, res) {
  res.writeHeader(200, { "Content-Type": "application/json" });
  res.end(JSON.stringify({ username: req.user.username }));
});

app.post("/register", function (req, res) {
  var username = req.body.username;
  var password = req.body.password;
  User.findByUsername(username)
    .exec()
    .then((user) => {
      if (user == null) {
        User.register({ username: username }, password);
        res.status(200).send({ msg: "All G" });
      } else {
        res.status(401).send({ msg: "Username exists" });
      }
    });
});

// get tasks for an authenticated user
app.get("/notes", connectEnsureLogin.ensureLoggedIn(), function (req, res) {
  console.log("Notes request for: " + req.user.username);
  User.findByUsername(req.user.username)
    .exec()
    .then((user) => {
      Tasks.find({ userId: user._id })
        .exec()
        .then((tasks) => {
          //console.log(tasks)
          res.writeHeader(200, { "Content-Type": "application/json" });
          res.end(JSON.stringify(tasks));
        });
    });
});

// post request for adding a task for an authenticated user
app.post(
  "/notes/add",
  connectEnsureLogin.ensureLoggedIn(),
  bodyParser.json({ extended: true }),
  function (req, res) {
    console.log("Add request for: " + req.user.username);
    const incomingData = req.body;
    var currentDateTime = Date.now();

    incomingData.taskCreationTime = currentDateTime;
    User.findByUsername(req.user.username)
      .exec()
      .then((user) => {
        incomingData.userId = user._id;
        const taskToAdd = new Tasks(incomingData);
        taskToAdd.save(function (err) {
          if (err) {
            res.writeHead(RES_TASK_ERR, "Cannot add the sent task", {
              "Content-Type": "text/plain",
            });
            res.end();
          } else {
            res.writeHead(200, "OK", { "Content-Type": "text/plain" });
            res.end();
          }
        });
      });
  }
);

// post request for deleting a task for an authenticated user
app.post(
  "/notes/delete",
  connectEnsureLogin.ensureLoggedIn(),
  bodyParser.json({ extended: true }),
  function (req, res) {
    console.log("Delete request for: " + req.user.username);
    const incomingData = req.body;
    User.findByUsername(req.user.username)
      .exec()
      .then((user) => {
        Tasks.deleteOne(
          { userId: user._id, _id: ObjectId(incomingData.taskID) },
          function (err) {
            if (err) {
              res.writeHead(RES_TASK_ERR, err.message, {
                "Content-Type": "text/plain",
              });
              res.end();
            } else {
              res.writeHead(200, { "Content-Type": "application/json" });
              res.end();
            }
          }
        );
      });
  }
);

// post request for editing a task for an authenticated user
app.post(
  "/notes/edit",
  connectEnsureLogin.ensureLoggedIn(),
  bodyParser.json({ extended: true }),
  function (req, res) {
    console.log("Edit request for: " + req.user.username);
    const incomingData = req.body;
    User.findByUsername(req.user.username)
      .exec()
      .then((user) => {
        incomingData.userId = user._id; // should be same, still updating just in case
        const editedTask = new Tasks(incomingData);
        Tasks.findOneAndUpdate(
          { _id: incomingData._id, userId: incomingData.userId },
          editedTask,
          function (err) {
            if (err) {
              res.writeHead(RES_TASK_ERR, "Gone", {
                "Content-Type": "text/plain",
              });
              res.end();
            } else {
              res.writeHead(RES_OK, "OK", { "Content-Type": "text/plain" });
              res.end();
            }
          }
        );
      });
  }
);

app.listen(process.env.PORT || 3000);
console.log("Server started");
